name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install


      - name: Archive build artifacts
        run: zip -r nodejs-app.zip .
        env:
          NODE_ENV: production

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          zip -r deploy-package.zip . -x node_modules/\*
          aws elasticbeanstalk create-application-version --application-name "NodejsApp" --version-label "v1" --source-bundle S3Bucket="YOUR_BUCKET_NAME",S3Key="deploy-package.zip"
